version: '1.0'
stages:
  - checkout
  - package
  - test
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: checkout
  climate_image:
    title: Building Docker Image
    type: build
    stage: package
    image_name: climate
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: ./development/Dockerfile
  unit_test:
    title: Running Unit tests
    image: '${{climate_image}}'
    stage: test 
    commands:
      - make linttest
  deploy_to_Balena:
    title: Deploying repository to Balena
    image: acmilabs/balena-cli:latest
    stage: deploy
    commands:
      - echo hello